version: "3.8"

services:
  peregerine_fmp:
    container_name: peregerine_fmp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8888:8888"  # Expose Jupyter Notebook
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    command: "uvicorn main:app --host 0.0.0.0 --port 8080 --reload"
