from sqlalchemy import Column, String, Date, Boolean, Integer, Num
from configs.database import Base
from sqlalchemy.dialects.postgresql import UUID, TIMESTAMP
import uuid

class Offers(Base):
    __tablename__ = "mcd_offers"
    
    offer_id = Column(Integer, primary_key=True)             
    campaign_id = Column(Integer, nullable=True)
    category_id = Column(Integer, nullable=True)
    category = Column(String, nullable=True)
    market = Column(String, nullable=True)    
    title = Column(String, nullable=True)    
    description = Column(String, nullable=True)

    terms_and_conditions = Column(String, nullable=True)
    has_barcode_image = Column(Boolean, nullable=True)
    redemption_limit = Column(Integer, nullable=True)
    payment_type = Column(Integer, nullable=True)
    redemption_count_unlimited =  Column(Boolean, nullable=True)
    code_type = Column(Integer, nullable=True)
    discount_percent = Column(Numeric(10, 0))
    discount_value = Column(Numeric(10, 0))
    status = Column(Integer, nullable=True)
    apply_geo_fence_filters = Column(Boolean, nullable=True)
    base_weight = Column(Integer, nullable=True)
    no_compete_group = Column(String, nullable=True)
    is_giftable = Column(Boolean, nullable=True)
    is_reward = Column(Boolean, nullable=True)
    is_respawning = Column(Boolean, nullable=True)
    respawns_in_days Column(Integer, nullable=True)
    enable_distance_weight = Column(Boolean, nullable=True)
    is_available_all_stores = Column(Boolean, nullable=True)
    promotional_image_description = Column(String, nullable=True)
    limit = Column(Integer, nullable=True)
    code_expiry_in_minutes = Column(Integer, nullable=True)
    is_sticky = Column(Boolean, nullable=True)
    sticky_expiration_days = Column(Integer, nullable=True)
    sticky_expiration_time_of_day = Column(Integer, nullable=True)
    offer_type = Column(String, nullable=True)
    respawn_start_time = Column(Integer, nullable=True)
    name = Column(String, nullable=True)
    respawns_in_minutes = Column(Integer, nullable=True)
    consumer_redemption_limit = Column(Integer, nullable=True)
    redemption_text = Column(String, nullable=True)
    days_of_week = Column(String, nullable=True)
    daily_start_time = Column(Integer, nullable=True)
    daily_end_time = Column(Integer, nullable=True)
    offer_start_time = Column(TIMESTAMP(timezone=True))
    offer_expire_time = Column(TIMESTAMP(timezone=True))
    when_last_updated_utc = Column(TIMESTAMP)