from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.dialects.postgresql import insert
from app.models.offers_model import Offers
from app.helpers.app_helper import to_uuid, to_datetime, to_int, to_decimal, to_bool

async def upsert_offers(db: AsyncSession, mongo_doc: dict):
    stmt=insert(Offers).values(
        offer_id=to_int(mongo_doc.get('offer_id')),
        campaign_id=to_int(mongo_doc.get('campaign_id')),
        category_id=to_int(mongo_doc.get('category_id')),
        category=mongo_doc.get('category'),
        market=mongo_doc.get('market'),
        title=mongo_doc.get('title'),
        description=mongo_doc.get('description'),
        terms_and_conditions=mongo_doc.get('terms_and_conditions'),
        has_barcode_image=to_bool(mongo_doc.get('has_barcode_image')),
        redemption_limit=to_int(mongo_doc.get('redemption_limit')),
        payment_type=to_int(mongo_doc.get('payment_type')),
        redemption_count_unlimited=to_bool(mongo_doc.get('redemption_count_unlimited')),
        code_type=to_int(mongo_doc.get('code_type')),
        discount_percent=to_decimal(mongo_doc.get('discount_percent')),
        discount_value=to_decimal(mongo_doc.get('discount_value')),
        status=to_int(mongo_doc.get('status')),
        apply_geo_fence_filters=to_bool(mongo_doc.get('apply_geo_fence_filters')),
        base_weight=to_int(mongo_doc.get('base_weight')),
        no_compete_group=mongo_doc.get('no_compete_group'),
        is_giftable=to_bool(mongo_doc.get('is_giftable')),
        is_reward=to_bool(mongo_doc.get('is_reward')),
        is_respawning=to_bool(mongo_doc.get('is_respawning')),
        respawns_in_days=to_int(mongo_doc.get('respawns_in_days')),
        enable_distance_weight=to_bool(mongo_doc.get('enable_distance_weight')),
        is_available_all_stores=to_bool(mongo_doc.get('is_available_all_stores')),
        promotional_image_description=mongo_doc.get('promotional_image_description'),
        limit=to_int(mongo_doc.get('limit')),
        code_expiry_in_minutes=to_int(mongo_doc.get('code_expiry_in_minutes')),
        is_sticky=to_bool(mongo_doc.get('is_sticky')),
        sticky_expiration_days=to_int(mongo_doc.get('sticky_expiration_days')),
        sticky_expiration_time_of_day=to_int(mongo_doc.get('sticky_expiration_time_of_day')),
        offer_type=mongo_doc.get('offer_type'),
        respawn_start_time=to_int(mongo_doc.get('respawn_start_time')),
        name=mongo_doc.get('name'),
        respawns_in_minutes=to_int(mongo_doc.get('respawns_in_minutes')),
        consumer_redemption_limit=to_int(mongo_doc.get('consumer_redemption_limit')),
        redemption_text=mongo_doc.get('redemption_text'),
        days_of_week=mongo_doc.get('days_of_week'),
        daily_start_time=to_int(mongo_doc.get('daily_start_time')),
        daily_end_time=to_int(mongo_doc.get('daily_end_time')),
        offer_start_time=to_datetime(mongo_doc.get('offer_start_time')),
        offer_expire_time=to_datetime(mongo_doc.get('offer_expire_time')),
        when_last_updated_utc=to_datetime(mongo_doc.get('when_last_updated_utc')),
    ).on_conflict_do_update(
        index_elements=["id"],
        set_={
            "offer_id": to_int(mongo_doc.get('offer_id')),
            "campaign_id": to_int(mongo_doc.get('campaign_id')),
            "category_id": to_int(mongo_doc.get('category_id')),
            "category": mongo_doc.get('category'),
            "market": mongo_doc.get('market'),
            "title": mongo_doc.get('title'),
            "description": mongo_doc.get('description'),
            "terms_and_conditions": mongo_doc.get('terms_and_conditions'),
            "has_barcode_image": to_bool(mongo_doc.get('has_barcode_image')),
            "redemption_limit": to_int(mongo_doc.get('redemption_limit')),
            "payment_type": to_int(mongo_doc.get('payment_type')),
            "redemption_count_unlimited": to_bool(mongo_doc.get('redemption_count_unlimited')),
            "code_type": to_int(mongo_doc.get('code_type')),
            "discount_percent": to_decimal(mongo_doc.get('discount_percent')),
            "discount_value": to_decimal(mongo_doc.get('discount_value')),
            "status": to_int(mongo_doc.get('status')),
            "apply_geo_fence_filters": to_bool(mongo_doc.get('apply_geo_fence_filters')),
            "base_weight": to_int(mongo_doc.get('base_weight')),
            "no_compete_group": mongo_doc.get('no_compete_group'),
            "is_giftable": to_bool(mongo_doc.get('is_giftable')),
            "is_reward": to_bool(mongo_doc.get('is_reward')),
            "is_respawning": to_bool(mongo_doc.get('is_respawning')),
            "respawns_in_days": to_int(mongo_doc.get('respawns_in_days')),
            "enable_distance_weight": to_bool(mongo_doc.get('enable_distance_weight')),
            "is_available_all_stores": to_bool(mongo_doc.get('is_available_all_stores')),
            "promotional_image_description": mongo_doc.get('promotional_image_description'),
            "limit": to_int(mongo_doc.get('limit')),
            "code_expiry_in_minutes": to_int(mongo_doc.get('code_expiry_in_minutes')),
            "is_sticky": to_bool(mongo_doc.get('is_sticky')),
            "sticky_expiration_days": to_int(mongo_doc.get('sticky_expiration_days')),
            "sticky_expiration_time_of_day": to_int(mongo_doc.get('sticky_expiration_time_of_day')),
            "offer_type": mongo_doc.get('offer_type'),
            "respawn_start_time": to_int(mongo_doc.get('respawn_start_time')),
            "name": mongo_doc.get('name'),
            "respawns_in_minutes": to_int(mongo_doc.get('respawns_in_minutes')),
            "consumer_redemption_limit": to_int(mongo_doc.get('consumer_redemption_limit')),
            "redemption_text": mongo_doc.get('redemption_text'),
            "days_of_week": mongo_doc.get('days_of_week'),
            "daily_start_time": to_int(mongo_doc.get('daily_start_time')),
            "daily_end_time": to_int(mongo_doc.get('daily_end_time')),
            "offer_start_time": to_datetime(mongo_doc.get('offer_start_time')),
            "offer_expire_time": to_datetime(mongo_doc.get('offer_expire_time')),
            "when_last_updated_utc": to_datetime(mongo_doc.get('when_last_updated_utc')),
        }
    )
    await db.execute(stmt)
    await db.commit()
